# Generated by Django 5.2.15 on 2026-06-27 04:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_add_purchase_requirement_recipe_landed_cost_coa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='packagingbomline',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='adj_prefix',
            field=models.CharField(default='ADJ', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='adv_prefix',
            field=models.CharField(default='ADV', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='cn_prefix',
            field=models.CharField(default='CN', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Pakistan', max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='decimal_precision',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='company',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_company', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='company',
            name='dn_prefix',
            field=models.CharField(default='DN', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='financial_year_start_month',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='company',
            name='grn_prefix',
            field=models.CharField(default='GRN', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='inv_prefix',
            field=models.CharField(default='INV', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='money_precision',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='near_expiry_threshold_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='company',
            name='pack_prefix',
            field=models.CharField(default='PACK', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='pay_prefix',
            field=models.CharField(default='PAY', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='po_prefix',
            field=models.CharField(default='PO', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='prod_prefix',
            field=models.CharField(default='PROD', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='receipt_footer_text',
            field=models.TextField(blank=True, default='Thank you for your business.'),
        ),
        migrations.AddField(
            model_name='company',
            name='receipt_paper_size',
            field=models.CharField(default='A4', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='receipt_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='bag_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='excess_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='final_payable_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='moisture_deduction',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='quality_deduction',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='supplier_claimed_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='packagingbom',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagingbom',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagingbom',
            name='packing_wastage_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='packagingbomline',
            name='remarks',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='packagingbomline',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagingbomline',
            name='wastage_allowance_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='operator',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='rejected_units',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='artwork_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_barcode_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='carton_barcode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='carton_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Packs per carton', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Product category e.g. Red Chili, Turmeric', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='erp.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_grinding_yield_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Expected % yield after grinding', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='grinding_loss_allowance_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='linked_raw_spice',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'raw'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powder_products', to='erp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_stock',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moisture_loss_allowance_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_type',
            field=models.CharField(blank=True, help_text='e.g. pouch, jar, bottle, box', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='adulteration_suspicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='cleanliness_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='color_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='deduction_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='dust_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='foreign_particles_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='grade_match_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='insects_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='inspector_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='packaging_condition_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='quality_decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('accepted_with_deduction', 'Accepted with Deduction'), ('partially_accepted', 'Partially Accepted'), ('rejected', 'Rejected'), ('held_for_review', 'Held for Review'), ('returned_to_supplier', 'Returned to Supplier')], default='accepted', max_length=40),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='smell_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='stones_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='artwork_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='batch_barcode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='design_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='label_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='packing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_batches', to='erp.packingorder'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='stock_state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hold', 'On Hold'), ('supplier_returnable', 'Supplier-Returnable'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('blocked', 'Blocked'), ('issued', 'Issued to Production'), ('sample', 'Sample'), ('promotional', 'Promotional'), ('rework', 'In Rework')], default='accepted', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplier',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_category',
            field=models.CharField(choices=[('raw_material', 'Raw Material Supplier'), ('packaging', 'Packaging Supplier'), ('grinding_service', 'Grinding Service'), ('transport', 'Transport Supplier'), ('general', 'General Service Supplier')], default='raw_material', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AlterField(
            model_name='packingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
    ]
