# Generated by Django 5.2.15 on 2026-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_structural_models_v7'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum retail price — D52 sales readiness', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard sale price — D52 sales readiness', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='adjustmentdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccountentry',
            name='account_type',
            field=models.CharField(choices=[('payable', 'Supplier Payable'), ('advance', 'Supplier Advance'), ('raw_inventory', 'Raw Material Inventory'), ('packaging_inventory', 'Packaging Inventory'), ('finished_inventory', 'Finished Goods Inventory'), ('cash', 'Cash'), ('bank', 'Bank'), ('purchase', 'Purchase Expense'), ('grinding', 'Grinding Expense'), ('packaging_exp', 'Packaging Expense'), ('wastage', 'Wastage/Loss'), ('discount', 'Discount Received'), ('adjustment', 'Stock Adjustment Gain/Loss'), ('customer_receivable', 'Customer Receivable'), ('sales_revenue', 'Sales Revenue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='grn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='landedcostallocation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='physicalstockcount',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='posted', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('quality_pending', 'Quality Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='posted', max_length=20),
        ),
    ]
