# Generated by Django 5.2.15 on 2026-06-30 16:59

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def normalize_customer_codes(apps, schema_editor):
    CustomerDistributor = apps.get_model("erp", "CustomerDistributor")
    seen = {}
    for customer in CustomerDistributor.objects.order_by("pk").only("pk", "code"):
        normalized = (customer.code or "").strip().upper()
        if not normalized:
            raise RuntimeError(f"Customer/distributor id={customer.pk} has an empty code.")
        if normalized in seen:
            raise RuntimeError(
                "Case-insensitive customer code collision before uq_customer_code_ci: "
                f"ids {seen[normalized]} and {customer.pk} both normalize to {normalized!r}. "
                "Resolve the duplicate codes and rerun the migration."
            )
        seen[normalized] = customer.pk
        if customer.code != normalized:
            customer.code = normalized
            customer.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_grnline_agreed_rate_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_customer_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customerdistributor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uq_customer_code_ci'),
        ),
    ]
