# Generated by Django 5.2.15 on 2026-07-01 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_customerdistributor_uq_customer_code_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('lock_key', models.CharField(max_length=180, unique=True)),
                ('locked_by', models.CharField(max_length=180)),
                ('locked_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('released', 'Released'), ('expired', 'Expired'), ('failed', 'Failed'), ('stale', 'Stale')], default='acquired', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idx_tasklock_status_exp')],
            },
        ),
    ]
