# Generated by Django 5.1.6 on 2026-06-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contactmessage_ip_address_contactmessage_spam_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('content', models.TextField(default='')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy policy'), ('terms', 'Terms and conditions'), ('return', 'Return policy'), ('refund', 'Refund policy'), ('shipping', 'Shipping policy'), ('cancellation', 'Cancellation policy'), ('cookie', 'Cookie policy'), ('food_disclosure', 'Food product disclosure'), ('allergen', 'Allergen disclosure'), ('business_identity', 'Business identity')], max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('requires_checkout_visibility', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy_pages',
                'ordering': ['page_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StaffMFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Authenticator app', max_length=120)),
                ('secret', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_mfa_devices',
            },
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['severity', 'created_at'], name='admin_activ_severit_decf5a_idx'),
        ),
        migrations.AddField(
            model_name='policypage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policy_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmfadevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='policypage',
            index=models.Index(fields=['slug', 'is_published'], name='policy_page_slug_4748a0_idx'),
        ),
        migrations.AddIndex(
            model_name='policypage',
            index=models.Index(fields=['page_type', 'is_published'], name='policy_page_page_ty_97cbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmfadevice',
            index=models.Index(fields=['user', 'confirmed'], name='staff_mfa_d_user_id_3d9c7a_idx'),
        ),
    ]
