# Generated by Django 5.1.15 on 2026-06-24 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customer_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city_pattern', models.CharField(help_text='Comma-separated city names or prefixes matched case-insensitively.', max_length=300)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_delivery_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_days_min', models.PositiveIntegerField(default=1)),
                ('estimated_days_max', models.PositiveIntegerField(default=3)),
                ('courier_hint', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'delivery_zones',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['active', 'sort_order'], name='delivery_zo_active_672d37_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='General', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faq_items',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['active', 'sort_order'], name='faq_items_active_8e03a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_email_verifications',
                'indexes': [models.Index(fields=['user', 'verified_at'], name='customer_em_user_id_92100a_idx'), models.Index(fields=['expires_at'], name='customer_em_expires_97bbaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_password_resets',
                'indexes': [models.Index(fields=['user', 'used_at'], name='customer_pa_user_id_1e9e91_idx'), models.Index(fields=['expires_at'], name='customer_pa_expires_9581c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, default='', max_length=120)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for dispatch'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed delivery'), ('returning', 'Returning'), ('returned', 'Returned')], default='pending', max_length=30)),
                ('estimated_delivery_min', models.DateField(blank=True, null=True)),
                ('estimated_delivery_max', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=300)),
                ('public_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='shop.order')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shop.deliveryzone')),
            ],
            options={
                'db_table': 'shipments',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='shipments_status_eb4ba9_idx'), models.Index(fields=['tracking_number'], name='shipments_trackin_cc256d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('category', models.CharField(choices=[('general', 'General question'), ('shipping', 'Shipping/tracking'), ('return', 'Return request'), ('refund', 'Refund request'), ('complaint', 'Complaint'), ('wholesale', 'Wholesale')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('waiting_customer', 'Waiting for customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='shop.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'indexes': [models.Index(fields=['user', 'created_at'], name='support_tic_user_id_eb143a_idx'), models.Index(fields=['order', 'category'], name='support_tic_order_i_8e2019_idx'), models.Index(fields=['status', 'updated_at'], name='support_tic_status_c8134f_idx')],
            },
        ),
    ]
