# Generated by Django 5.2.15 on 2026-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_deliveryzone_faqitem_customeremailverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Legacy portal threshold; use ERP Product minimum_stock for operations.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=100, help_text='Legacy portal value retained for migration compatibility; ERP stock drives availability.'),
        ),
    ]
