# Generated by Django 5.2.15 on 2026-07-01 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('erp', '0012_scheduledtasklock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crminteraction',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('customer__isnull', False), ('opportunity__isnull', False), _connector='OR'), name='crm_interaction_has_subject'),
        ),
        migrations.AddConstraint(
            model_name='followuptask',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('customer__isnull', False), ('opportunity__isnull', False), _connector='OR'), name='crm_followup_has_subject'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('customer__isnull', False), _connector='OR'), name='crm_opportunity_has_party'),
        ),
    ]
