# Generated by Django 5.1.3 on 2026-06-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_grammage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(default='cod', max_length=50)),
                ('notes', models.TextField(default='')),
                ('total', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('delivery_charge', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('weight_option', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
