# Generated by Django 5.1.6 on 2026-06-23 19:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def parse_weight(raw_weight):
    raw = str(raw_weight or "").strip().lower()
    if raw.endswith("kg"):
        return Decimal(raw[:-2]), "kg"
    if raw.endswith("g"):
        return Decimal(raw[:-1]), "g"
    return Decimal("200"), "g"


def create_variants_from_products(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    ProductVariant = apps.get_model("shop", "ProductVariant")
    OrderItem = apps.get_model("shop", "OrderItem")

    for product in Product.objects.all():
        payloads = []
        grammage_options = product.grammage_options or {}
        if grammage_options:
            for sort_order, (grams, price) in enumerate(grammage_options.items()):
                payloads.append(
                    {
                        "sku": f"AURA-{product.id}-{grams}g",
                        "weight_value": Decimal(str(grams)),
                        "weight_unit": "g",
                        "price": Decimal(str(price)),
                        "old_price": product.old_price,
                        "sort_order": sort_order,
                    }
                )
        else:
            weight_value, weight_unit = parse_weight(product.weight)
            payloads.append(
                {
                    "sku": f"AURA-{product.id}-default",
                    "weight_value": weight_value,
                    "weight_unit": weight_unit,
                    "price": product.price,
                    "old_price": product.old_price,
                    "sort_order": 0,
                }
            )

        created_variants = []
        for payload in payloads:
            variant, _ = ProductVariant.objects.update_or_create(
                sku=payload["sku"],
                defaults={
                    "product": product,
                    "weight_value": payload["weight_value"],
                    "weight_unit": payload["weight_unit"],
                    "price": payload["price"],
                    "old_price": payload["old_price"],
                    "active": True,
                    "sellable": True,
                    "stock_quantity": 100,
                    "sort_order": payload["sort_order"],
                },
            )
            created_variants.append(variant)

        for order_item in OrderItem.objects.filter(product_id=product.id, variant__isnull=True):
            matched_variant = None
            if order_item.weight_option:
                for variant in created_variants:
                    expected_weight = f"{variant.weight_value.normalize():f}".rstrip("0").rstrip(".")
                    if order_item.weight_option.lower() == f"{expected_weight}{variant.weight_unit}":
                        matched_variant = variant
                        break
            if not matched_variant and created_variants:
                matched_variant = created_variants[0]
            if matched_variant:
                order_item.variant_id = matched_variant.id
                order_item.save(update_fields=["variant"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('weight_value', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight_unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms')], default='g', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('active', models.BooleanField(default=True)),
                ('sellable', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'weight_value', 'weight_unit'), name='unique_product_weight_variant'),
        ),
        migrations.RunPython(create_variants_from_products, migrations.RunPython.noop),
    ]
