# Generated by Django 5.1.6 on 2026-06-23 19:36

import secrets

from django.db import migrations, models


def populate_order_references(apps, schema_editor):
    Order = apps.get_model("shop", "Order")
    for order in Order.objects.filter(reference=""):
        reference = secrets.token_hex(8)
        while Order.objects.filter(reference=reference).exists():
            reference = secrets.token_hex(8)
        order.reference = reference
        order.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_bundle_old_price_alter_bundle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.RunPython(populate_order_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
    ]
