# Generated by Django 5.1.6 on 2026-06-24 07:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_idempotency_key_order_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('object_repr', models.CharField(blank=True, default='', max_length=300)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_activity_logs',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_status_logs',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cod', 'Cash on delivery'), ('jazzcash', 'JazzCash manual verification'), ('easypaisa', 'Easypaisa manual verification'), ('bank_transfer', 'Bank transfer manual verification'), ('manual', 'Manual')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_verification', 'Awaiting verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('shelf_life_months', models.PositiveIntegerField(default=0)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('depleted', 'Depleted'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_batches',
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('failed', 'Failed')], default='requested', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'refund_requests',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('closed', 'Closed')], default='requested', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'return_requests',
            },
        ),
        migrations.CreateModel(
            name='SpiceProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spice_form', models.CharField(choices=[('whole', 'Whole'), ('ground', 'Ground'), ('blend', 'Blend'), ('masala', 'Masala'), ('herb', 'Herb'), ('salt', 'Salt'), ('other', 'Other')], default='other', max_length=30)),
                ('organic_claim', models.BooleanField(default=False)),
                ('premium_claim', models.BooleanField(default=False)),
                ('purity_claim_text', models.CharField(blank=True, default='', max_length=300)),
                ('claim_evidence_note', models.TextField(blank=True, default='')),
                ('claim_approved', models.BooleanField(default=False)),
                ('heat_level', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra_hot', 'Extra hot')], default='none', max_length=30)),
                ('flavor_notes', models.TextField(blank=True, default='')),
                ('aroma_notes', models.TextField(blank=True, default='')),
                ('ingredient_disclosure', models.TextField(blank=True, default='')),
                ('allergen_statement', models.TextField(blank=True, default='')),
                ('storage_instructions', models.TextField(blank=True, default='')),
                ('usage_instructions', models.TextField(blank=True, default='')),
                ('cuisine_tags', models.CharField(blank=True, default='', max_length=500)),
                ('recipe_suitability_tags', models.CharField(blank=True, default='', max_length=500)),
                ('packaging_type', models.CharField(blank=True, default='', max_length=200)),
                ('packaging_size_note', models.CharField(blank=True, default='', max_length=300)),
                ('food_grade_packaging_note', models.TextField(blank=True, default='')),
                ('freshness_note', models.TextField(blank=True, default='')),
                ('shelf_life_months', models.PositiveIntegerField(default=0)),
                ('expiry_display_policy', models.CharField(blank=True, default='', max_length=300)),
                ('manufacturing_display_policy', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spice_product_profiles',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('cancellation_restore', 'Cancellation restore'), ('return_restore', 'Return restore'), ('expiry_writeoff', 'Expiry writeoff'), ('damage_writeoff', 'Damage writeoff'), ('manual_correction', 'Manual correction')], max_length=40)),
                ('quantity_delta', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, default='', max_length=80)),
                ('reference_id', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_ledger',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('awaiting_verification', 'Awaiting verification'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories_name_98d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference'], name='orders_referen_4ee262_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'category'], name='products_active_4a39fe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'active'], name='products_feature_315723_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'active'], name='product_var_product_6d4d71_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='product_var_sku_3a95f0_idx'),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shop.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='shop.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='shop.order'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='shop.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='shop.order'),
        ),
        migrations.AddField(
            model_name='spiceproductprofile',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spice_profile', to='shop.product'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger', to='shop.productbatch'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='shop.productvariant'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['actor', 'created_at'], name='admin_activ_actor_i_18f9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['model_name', 'object_id'], name='admin_activ_model_n_ac106e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['order', 'created_at'], name='order_statu_order_i_b51d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payment_tra_order_i_650087_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'status'], name='payment_tra_provide_2e4ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['batch_number'], name='product_bat_batch_n_965614_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product_variant', 'status', 'expiry_date'], name='product_bat_product_d79ee5_idx'),
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='batch_available_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='batch_reserved_quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['product_variant', 'created_at'], name='stock_ledge_product_0878ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_ledge_referen_f43b64_idx'),
        ),
    ]
