# Generated by Django 5.1.6 on 2026-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_adminactivitylog_orderstatuslog_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='spam_status',
            field=models.CharField(choices=[('new', 'New'), ('spam', 'Spam'), ('reviewed', 'Reviewed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='suspicious_order',
            field=models.BooleanField(default=False),
        ),
    ]
