# Generated by Django 5.2.17 on 2026-08-31 17:43
#
# Reworked to be safe against databases that already contain Category rows,
# AND (second rework) to be safe to re-run against a database where a
# previous deploy attempt already applied some or all of this migration's
# DDL but the app crashed/restarted before Django could record the
# migration as applied (e.g. multiple app instances running `migrate`
# concurrently on startup, or the process being killed mid-migration).
# That leaves the `categories` table with the slug column/constraints/
# indexes already in place while `django_migrations` still says 0015 is
# pending — so every subsequent restart reruns this migration from
# scratch and immediately hits "relation ... already exists" (or
# "column ... already exists"), and the app can never come up.
#
# The original version of this migration added `slug` with unique=True in a
# single AddField. On any non-empty `categories` table PostgreSQL back-fills
# every existing row with the field default ('') and then tries to build
# categories_slug_key over a column where every value is identical, which
# fails with:
#     could not create unique index "categories_slug_key"
#     DETAIL: Key (slug)=() is duplicated.
#
# The fix is the standard three-step sequence, kept inside this one migration
# so the migration graph and any already-applied environment stay untouched:
#   1. add the column WITHOUT the unique constraint
#   2. populate it
#   3. apply unique=True and the index
# PostgreSQL DDL is transactional, so all three steps commit or roll back
# together.
#
# Each of those three steps is now wrapped so that if the underlying DDL has
# already been applied to the database (by an earlier attempt that never
# made it into django_migrations), the step is skipped instead of raising.
# Each attempt runs inside its own savepoint (transaction.atomic()) so a
# "already exists" error only rolls back that one step, not the whole
# migration transaction that Postgres would otherwise abort wholesale.
#
# Separately, and this turned out to be the actual root cause of the crash
# loop (reproduced locally against a completely fresh, never-touched
# PostgreSQL database — this was not only a partial-reapply problem):
# django.db.models.SlugField defaults db_index=True even when you don't ask
# for it. Step 1 originally added the column as a plain (non-unique)
# SlugField, which under the hood already queues PostgreSQL's "_like"
# opclass index (needed for LIKE/startswith lookups) as *deferred* SQL on
# the schema editor. Step 3 then converts that same field to unique=True,
# which — because the field is still a SlugField with db_index defaulting
# to True — queues that exact same "_like" index a *second* time. Both
# deferred statements share one deterministic name and only run at the very
# end of the migration's transaction, so the first one succeeds and the
# second fails with "already exists", aborting the whole migration — on
# every single attempt, not just a retried one. The fix is to make the
# intermediate (step 1) field explicitly db_index=False, so only the final
# unique=True field (step 3) ever queues that index, exactly once.

from django.db import migrations, models, transaction
from django.db.utils import DatabaseError
from django.utils.text import slugify


def _is_already_exists_error(exc: DatabaseError) -> bool:
    message = str(exc).lower()
    return "already exists" in message or "duplicate column" in message


def backfill_category_slugs(apps, schema_editor):
    Category = apps.get_model("shop", "Category")

    taken = set()
    for category in Category.objects.order_by("pk").iterator():
        # allow_unicode=False keeps slugs inside the [-a-zA-Z0-9_]+ character
        # class that the `<slug:slug>` URL converter accepts. Names that are
        # entirely non-Latin slugify to '' and fall back to the primary key,
        # so no row can end up with an empty slug.
        base = slugify(category.name)[:210] or f"category-{category.pk}"

        candidate = base
        suffix = 2
        while candidate in taken:
            candidate = f"{base}-{suffix}"
            suffix += 1

        taken.add(candidate)
        if category.slug != candidate:
            category.slug = candidate
            category.save(update_fields=["slug"])


def add_slug_column(apps, schema_editor):
    """
    Idempotent equivalent of AddField(slug, unique=False). db_index is
    explicitly disabled here (SlugField defaults it to True) so this step
    does not queue PostgreSQL's "_like" opclass index — that index is
    queued exactly once, by add_slug_unique_constraint below.
    """
    Category = apps.get_model("shop", "Category")
    field = models.SlugField(blank=True, default="", max_length=220, db_index=False)
    field.set_attributes_from_name("slug")
    try:
        with transaction.atomic(using=schema_editor.connection.alias):
            schema_editor.add_field(Category, field)
    except DatabaseError as exc:
        if not _is_already_exists_error(exc):
            raise


def remove_slug_column(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    field = models.SlugField(blank=True, default="", max_length=220, db_index=False)
    field.set_attributes_from_name("slug")
    schema_editor.remove_field(Category, field)


def add_slug_unique_constraint(apps, schema_editor):
    """Idempotent equivalent of AlterField(slug, unique=True)."""
    Category = apps.get_model("shop", "Category")
    from_field = models.SlugField(blank=True, default="", max_length=220, db_index=False)
    from_field.set_attributes_from_name("slug")
    to_field = models.SlugField(blank=True, max_length=220, unique=True)
    to_field.set_attributes_from_name("slug")
    try:
        with transaction.atomic(using=schema_editor.connection.alias):
            schema_editor.alter_field(Category, from_field, to_field)
    except DatabaseError as exc:
        if not _is_already_exists_error(exc):
            raise


def revert_slug_unique_constraint(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    from_field = models.SlugField(blank=True, max_length=220, unique=True)
    from_field.set_attributes_from_name("slug")
    to_field = models.SlugField(blank=True, default="", max_length=220, db_index=False)
    to_field.set_attributes_from_name("slug")
    schema_editor.alter_field(Category, from_field, to_field)


def add_slug_index(apps, schema_editor):
    """Idempotent equivalent of AddIndex(categories_slug_b4303a_idx)."""
    Category = apps.get_model("shop", "Category")
    index = models.Index(fields=['slug'], name='categories_slug_b4303a_idx')
    try:
        with transaction.atomic(using=schema_editor.connection.alias):
            schema_editor.add_index(Category, index)
    except DatabaseError as exc:
        if not _is_already_exists_error(exc):
            raise


def remove_slug_index(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    index = models.Index(fields=['slug'], name='categories_slug_b4303a_idx')
    schema_editor.remove_index(Category, index)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_seed_1kg_variants_and_loved_products'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_slug_column, remove_slug_column),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='category',
                    name='slug',
                    field=models.SlugField(blank=True, default='', max_length=220),
                ),
            ],
        ),
        migrations.RunPython(
            backfill_category_slugs,
            migrations.RunPython.noop,
            elidable=False,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_slug_unique_constraint, revert_slug_unique_constraint),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='category',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=220, unique=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_slug_index, remove_slug_index),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='category',
                    index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
                ),
            ],
        ),
    ]
