# Generated by Django 5.2.15 on 2026-06-26 06:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tax_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_identifier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplier',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='is_tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='withholding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddIndex(
            model_name='adjustmentdocument',
            index=models.Index(fields=['number'], name='idx_adjustment_number'),
        ),
        migrations.AddIndex(
            model_name='adjustmentdocument',
            index=models.Index(fields=['adjustment_type', 'status'], name='idx_adjustment_type_status'),
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['number'], name='idx_grn_number'),
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['supplier', 'status'], name='idx_grn_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['grn_date'], name='idx_grn_date'),
        ),
        migrations.AddIndex(
            model_name='packingorder',
            index=models.Index(fields=['number'], name='idx_packing_number'),
        ),
        migrations.AddIndex(
            model_name='packingorder',
            index=models.Index(fields=['status'], name='idx_packing_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='idx_product_type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='idx_product_barcode'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['number'], name='idx_production_number'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='idx_production_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['number'], name='idx_po_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='idx_po_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='idx_po_order_date'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'batch_type'], name='idx_batch_product_type'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_number'], name='idx_batch_number'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['warehouse', 'batch_type'], name='idx_batch_wh_type'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='idx_batch_expiry'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['source_document_type', 'source_document_number'], name='idx_batch_source_doc'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['batch', 'direction'], name='idx_stock_ledger_batch_dir'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['product', 'transaction_date'], name='idx_stock_ledger_product_date'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['source_document_type', 'source_document_number'], name='idx_stock_ledger_doc'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['number'], name='idx_supplier_invoice_no'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier', 'status'], name='idx_invoice_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['invoice_date'], name='idx_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['due_date'], name='idx_invoice_due_date'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['supplier', 'transaction_date'], name='idx_supplier_ledger_date'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['source_document_type', 'source_document_number'], name='idx_supplier_ledger_doc'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['balance_effect'], name='idx_supplier_ledger_effect'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['number'], name='idx_supplier_payment_no'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_type'], name='idx_payment_supplier_type'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
    ]
