# Generated by Django 5.2.15 on 2026-06-26 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_supplier_tax_category_supplier_tax_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('account_type', models.CharField(choices=[('payable', 'Supplier Payable'), ('advance', 'Supplier Advance'), ('raw_inventory', 'Raw Material Inventory'), ('packaging_inventory', 'Packaging Inventory'), ('finished_inventory', 'Finished Goods Inventory'), ('cash', 'Cash'), ('bank', 'Bank'), ('purchase', 'Purchase Expense'), ('grinding', 'Grinding Expense'), ('packaging_exp', 'Packaging Expense'), ('wastage', 'Wastage/Loss'), ('discount', 'Discount Received'), ('adjustment', 'Stock Adjustment Gain/Loss')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('standard_batch_size', models.DecimalField(decimal_places=3, max_digits=18)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_date', models.DateField()),
                ('is_confidential', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes_approved', to=settings.AUTH_USER_MODEL)),
                ('batch_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unitofmeasure')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='erp.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('tolerance_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=160)),
                ('ingredient', models.ForeignKey(limit_choices_to={'product_type__in': ['raw', 'powder']}, on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='erp.recipe')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_grn_count', models.PositiveIntegerField(default=0)),
                ('total_rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_shortage_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('average_yield_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('quality_complaints', models.PositiveIntegerField(default=0)),
                ('payment_disputes', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='erp.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(blank=True, max_length=40)),
                ('advance_required', models.BooleanField(default=False)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('discount_terms', models.TextField(blank=True)),
                ('delivery_responsibility', models.CharField(blank=True, max_length=80)),
                ('quality_deduction_rules', models.TextField(blank=True)),
                ('shortage_tolerance_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('replacement_policy', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='erp.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('cost_category', models.CharField(choices=[('freight', 'Freight/Transport'), ('loading', 'Loading/Unloading'), ('customs', 'Customs/Duty'), ('inspection', 'Inspection Fee'), ('other', 'Other Direct Cost')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocation_base', models.CharField(default='quantity', help_text='quantity or value', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_costs', to='erp.grn')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['grn'], name='idx_landed_cost_grn')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Demand'), ('low_stock', 'Low Stock Alert'), ('production', 'Production Planning'), ('seasonal', 'Seasonal Bulk Purchase'), ('packaging', 'Packaging Shortage'), ('owner', 'Owner/Director Instruction')], default='manual', max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='erp.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='idx_pr_status'), models.Index(fields=['required_by_date'], name='idx_pr_required_date')],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status'], name='idx_recipe_status'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uq_recipe_code_version'),
        ),
    ]
