# Generated by Django 5.2.15 on 2026-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_v6_model_spec_gaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='code',
            field=models.CharField(max_length=40),
        ),
    ]
