# Generated by Django 5.2.15 on 2026-06-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_recipe_code_non_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cashbankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='grn',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns_received', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='grn',
            name='delivery_note_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='grn',
            name='received_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='grn',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_statement_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='clearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='cash/bank_transfer/cheque/online/mobile_wallet/adjustment', max_length=40),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='po_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cashbankaccount',
            name='account_type',
            field=models.CharField(default='cash', help_text='cash or bank', max_length=20),
        ),
    ]
