# Generated by Django 5.2.15 on 2026-06-28 09:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_system_settings_doc_series_cancelled_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('batch_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.stockbatch')),
                ('opening_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.openingbalance')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('count_date', models.DateField()),
                ('count_type', models.CharField(choices=[('full', 'Full Count'), ('cycle', 'Cycle Count'), ('item', 'Item-Wise Count'), ('batch', 'Batch-Wise Count'), ('warehouse', 'Warehouse-Wise Count')], default='full', max_length=20)),
                ('freeze_stock', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psc_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalStockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('physical_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('variance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('adjustment_number', models.CharField(blank=True, max_length=40)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.stockbatch')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.physicalstockcount')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('grn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.grnline')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.supplierinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocation_type', models.CharField(choices=[('payment', 'Payment'), ('advance_adjustment', 'Advance Adjustment'), ('debit_note', 'Debit Note')], default='payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.supplierinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='erp.supplierpayment')),
            ],
            options={
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
