# Generated by Django 5.2.15 on 2026-06-30 05:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_d52_sales_readiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grnline',
            name='agreed_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='rate_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='rate_variance_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='rate_variance_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='agreed_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='rate_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='rate_variance_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='rate_variance_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='expiry_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('current', 'Current'), ('near_expiry', 'Near Expiry'), ('expired', 'Expired')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='agreed_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='rate_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='rate_variance_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='rate_variance_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.CreateModel(
            name='CustomerDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('customer_type', models.CharField(choices=[('retailer', 'Retailer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('restaurant', 'Restaurant'), ('caterer', 'Caterer'), ('institution', 'Institution'), ('ecommerce', 'Ecommerce'), ('export_buyer', 'Export Buyer'), ('walk_in', 'Walk In'), ('other', 'Other')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('province_state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Pakistan', max_length=80)),
                ('tax_registration_number', models.CharField(blank=True, max_length=80)),
                ('local_tax_number', models.CharField(blank=True, help_text='NTN/STRN or local equivalent', max_length=80)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=160)),
                ('preferred_price_list', models.CharField(blank=True, max_length=120)),
                ('sales_channel', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('distributor', 'Distributor'), ('horeca', 'HORECA'), ('ecommerce', 'Ecommerce'), ('export', 'Export')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_label', models.CharField(max_length=80)),
                ('recipient_contact', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('province_state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Pakistan', max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='erp.customerdistributor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer__code', '-is_default', 'address_label'],
            },
        ),
        migrations.CreateModel(
            name='DailyProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_number', models.CharField(max_length=40, unique=True)),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('general', 'General'), ('custom', 'Custom')], default='general', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=120)),
                ('machine', models.CharField(blank=True, max_length=120)),
                ('raw_quantity_issued', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('powder_quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('finished_quantity_packed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('grinding_wastage_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('packing_wastage_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('issue_category', models.CharField(choices=[('none', 'None'), ('machine_issue', 'Machine Issue'), ('labor_issue', 'Labor Issue'), ('material_quality_issue', 'Material Quality Issue'), ('packaging_issue', 'Packaging Issue'), ('power_issue', 'Power Issue'), ('other', 'Other')], default='none', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_logs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finished_goods_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_shift_logs', to='erp.stockbatch')),
                ('packing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_logs', to='erp.packingorder')),
                ('powder_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powder_shift_logs', to='erp.stockbatch')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_logs', to='erp.productionorder')),
                ('raw_material_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_shift_logs', to='erp.stockbatch')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs_supervised', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
            options={
                'ordering': ['-log_date', 'shift', 'log_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency_description', models.CharField(max_length=160)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('command_name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('expiry_refresh', 'Expiry Refresh'), ('overdue_refresh', 'Overdue Refresh'), ('backup', 'Backup'), ('health_check', 'Health Check'), ('report_snapshot', 'Report Snapshot'), ('cleanup', 'Cleanup'), ('other', 'Other')], max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=20)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('manual', 'Manual'), ('cron', 'Cron'), ('management_command', 'Management Command')], default='system', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_type', 'status', 'started_at'], name='idx_joblog_type_status')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_number', models.CharField(max_length=40, unique=True)),
                ('item_type', models.CharField(choices=[('raw_spice', 'Raw Spice'), ('packaging_material', 'Packaging Material'), ('powder_product', 'Powder Product'), ('service', 'Service')], max_length=30)),
                ('agreed_rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('maximum_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('seasonal', 'Seasonal'), ('negotiated', 'Negotiated'), ('spot', 'Spot'), ('contract', 'Contract')], default='fixed', max_length=20)),
                ('payment_terms_reference', models.CharField(blank=True, max_length=160)),
                ('delivery_terms_reference', models.CharField(blank=True, max_length=160)),
                ('quality_grade_reference', models.CharField(blank=True, max_length=120)),
                ('tolerance_percentage', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_agreements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_price_agreements', to='erp.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_agreements', to='erp.supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', 'supplier__code', 'product__code'],
            },
        ),
        migrations.AddField(
            model_name='grnline',
            name='rate_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='erp.supplierpriceagreement'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='rate_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='erp.supplierpriceagreement'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='rate_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='erp.supplierpriceagreement'),
        ),
        migrations.AddIndex(
            model_name='customerdistributor',
            index=models.Index(fields=['customer_type', 'sales_channel', 'status'], name='idx_customer_segment'),
        ),
        migrations.AddIndex(
            model_name='customerdistributor',
            index=models.Index(fields=['city', 'country'], name='idx_customer_location'),
        ),
        migrations.AddIndex(
            model_name='customerdistributor',
            index=models.Index(fields=['phone'], name='idx_customer_phone'),
        ),
        migrations.AddConstraint(
            model_name='customerdistributor',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', 0), _connector='OR'), name='ck_customer_credit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='customershippingaddress',
            constraint=models.UniqueConstraint(fields=('customer', 'address_label'), name='uq_customer_address_label'),
        ),
        migrations.AddIndex(
            model_name='dailyproductionlog',
            index=models.Index(fields=['log_date', 'shift'], name='idx_prodlog_date_shift'),
        ),
        migrations.AddIndex(
            model_name='dailyproductionlog',
            index=models.Index(fields=['status'], name='idx_prodlog_status'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductionlog',
            constraint=models.CheckConstraint(condition=models.Q(('raw_quantity_issued__gte', 0)), name='ck_prodlog_raw_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductionlog',
            constraint=models.CheckConstraint(condition=models.Q(('powder_quantity_received__gte', 0)), name='ck_prodlog_powder_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductionlog',
            constraint=models.CheckConstraint(condition=models.Q(('finished_quantity_packed__gte', 0)), name='ck_prodlog_finished_nonneg'),
        ),
        migrations.AddIndex(
            model_name='supplierpriceagreement',
            index=models.Index(fields=['supplier', 'product', 'unit', 'status'], name='idx_rate_lookup'),
        ),
        migrations.AddIndex(
            model_name='supplierpriceagreement',
            index=models.Index(fields=['effective_date', 'expiry_date'], name='idx_rate_validity'),
        ),
        migrations.AddConstraint(
            model_name='supplierpriceagreement',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_rate__gt', 0)), name='ck_rate_agreed_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpriceagreement',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gte', models.F('effective_date'))), name='ck_rate_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='supplierpriceagreement',
            constraint=models.CheckConstraint(condition=models.Q(('tolerance_percentage__gte', 0)), name='ck_rate_tolerance_nonneg'),
        ),
    ]
