# Generated by Django 5.2.15 on 2026-07-01 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_map_exact_catalog_skus'),
        ('shop', '0013_alter_productvariant_low_stock_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledgerentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sales.salesinvoice'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(fields=('order',), name='sales_one_full_return_per_order'),
        ),
    ]
